services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: redmine
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Missing POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U redmine -d redmine"]
      interval: 5s
      timeout: 5s
      retries: 20
  redmine:
    image: ${IMAGE_URI:?Missing IMAGE_URI}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: ${POSTGRES_PASSWORD:?Missing POSTGRES_PASSWORD}
      REDMINE_SECRET_KEY_BASE: ${REDMINE_SECRET_KEY_BASE:?Missing SECRET_KEY}
      RAILS_ENV: production
      REDMINE_PLUGINS_MIGRATE: "1"
    volumes:
      - redmine_files:/usr/src/redmine/files
volumes:
  pg_data:
  redmine_files:
